package hibernateModel;
// Generated 03-abr-2023 13:06:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private Integer idAnuncio;
     private Categoria categoria;
     private Usuario usuario;
     private String titulo;
     private String descripcion;
     private BigDecimal precio;
     private String direccion;
     private byte[] imagen;
     private String estado;
     private String revision;
    
     private Set chats = new HashSet(0);

    public Anuncio() {
    }

	
    public Anuncio(Categoria categoria, Usuario usuario, String titulo, String descripcion, BigDecimal precio, String direccion, String estado, String revision) {
        this.categoria = categoria;
        this.usuario = usuario;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.precio = precio;
        this.direccion = direccion;
        this.estado = estado;
        this.revision = revision;
    }
    public Anuncio(Categoria categoria, Usuario usuario, String titulo, String descripcion, BigDecimal precio, String direccion, byte[] imagen, String estado,String revision, Set chats) {
       this.categoria = categoria;
       this.usuario = usuario;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.precio = precio;
       this.direccion = direccion;
       this.imagen = imagen;
       this.estado = estado;
       this.revision = revision;
       this.chats = chats;
    }
   
    public Integer getIdAnuncio() {
        return this.idAnuncio;
    }
    
    public void setIdAnuncio(Integer idAnuncio) {
        this.idAnuncio = idAnuncio;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public byte[] getImagen() {
        return this.imagen;
    }
    
    public void setImagen(byte[] imagen) {
        this.imagen = imagen;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getRevision() {
        return revision;
    }

    public void setRevision(String revision) {
        this.revision = revision;
    }
   
    
    
    public Set getChats() {
        return this.chats;
    }
    
    public void setChats(Set chats) {
        this.chats = chats;
    }




}


