package hibernateModel;
// Generated 03-abr-2023 13:06:50 by Hibernate Tools 4.3.1


import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.SortedSet;

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private Integer idChat;
     private Anuncio anuncio;
     private Usuario usuarioByIdUuarioInteresado;
     private Usuario usuarioByIdPropietario;
     private Date fechaChat;
     private SortedSet mensajes;
     private boolean revisado_Propietario;
     private boolean revisado_Interesado;

    public Chat() {
    }

	
    public Chat(Anuncio anuncio, Usuario usuarioByIdUuarioInteresado, Usuario usuarioByIdPropietario) {
        this.anuncio = anuncio;
        this.usuarioByIdUuarioInteresado = usuarioByIdUuarioInteresado;
        this.usuarioByIdPropietario = usuarioByIdPropietario;
    }
    public Chat(Anuncio anuncio, Usuario usuarioByIdUuarioInteresado, Usuario usuarioByIdPropietario, Date fechaChat, SortedSet mensajes) {
       this.anuncio = anuncio;
       this.usuarioByIdUuarioInteresado = usuarioByIdUuarioInteresado;
       this.usuarioByIdPropietario = usuarioByIdPropietario;
       this.fechaChat = fechaChat;
       this.mensajes = mensajes;
    }

     public Chat(Anuncio anuncio, Usuario usuarioByIdUuarioInteresado, Usuario usuarioByIdPropietario, Date fechaChat) {
       this.anuncio = anuncio;
       this.usuarioByIdUuarioInteresado = usuarioByIdUuarioInteresado;
       this.usuarioByIdPropietario = usuarioByIdPropietario;
       this.fechaChat = fechaChat;
      
    }
   
    public Integer getIdChat() {
        return this.idChat;
    }
    
    public void setIdChat(Integer idChat) {
        this.idChat = idChat;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public Usuario getUsuarioByIdUuarioInteresado() {
        return this.usuarioByIdUuarioInteresado;
    }
    
    public void setUsuarioByIdUuarioInteresado(Usuario usuarioByIdUuarioInteresado) {
        this.usuarioByIdUuarioInteresado = usuarioByIdUuarioInteresado;
    }
    public Usuario getUsuarioByIdPropietario() {
        return this.usuarioByIdPropietario;
    }
    
    public void setUsuarioByIdPropietario(Usuario usuarioByIdPropietario) {
        this.usuarioByIdPropietario = usuarioByIdPropietario;
    }
    public Date getFechaChat() {
        return this.fechaChat;
    }
    
    public void setFechaChat(Date fechaChat) {
        this.fechaChat = fechaChat;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(SortedSet mensajes) {
        this.mensajes = mensajes;
    }

    public boolean isRevisado_Propietario() {
        return revisado_Propietario;
    }

    public void setRevisado_Propietario(boolean revisado_Propietario) {
        this.revisado_Propietario = revisado_Propietario;
    }

    public boolean isRevisado_Interesado() {
        return revisado_Interesado;
    }

    public void setRevisado_Interesado(boolean revisado_Interesado) {
        this.revisado_Interesado = revisado_Interesado;
    }




}


