package hibernateModel;
// Generated 03-abr-2023 13:06:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private Integer idCompra;
     private Anuncio anuncio;
     private Usuario usuario;
     private Date fechaCommpra;
     private BigDecimal precioFinal;
     private boolean pagado;
     private boolean revisado;

    public Compra() {
    }

    public Compra(Anuncio anuncio, Usuario usuario, Date fechaCommpra, BigDecimal precioFinal, boolean pagado, boolean revisado) {
       this.anuncio = anuncio;
       this.usuario = usuario;
       this.fechaCommpra = fechaCommpra;
       this.precioFinal = precioFinal;
       this.pagado = pagado;
       this.revisado = revisado;
    }

    

    public Integer getIdCompra() {
        return idCompra;
    }

    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
   
   
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCommpra() {
        return this.fechaCommpra;
    }
    
    public void setFechaCommpra(Date fechaCommpra) {
        this.fechaCommpra = fechaCommpra;
    }
    public BigDecimal getPrecioFinal() {
        return this.precioFinal;
    }
    
    public void setPrecioFinal(BigDecimal precioFinal) {
        this.precioFinal = precioFinal;
    }
    public boolean isPagado() {
        return this.pagado;
    }
    
    public void setPagado(boolean pagado) {
        this.pagado = pagado;
    }

    public boolean isRevisado() {
        return revisado;
    }

    public void setRevisado(boolean revisado) {
        this.revisado = revisado;
    }




}


