package hibernateModel;
// Generated 31-may-2023 18:36:26 by Hibernate Tools 4.3.1



/**
 * Favoritos generated by hbm2java
 */
public class Favoritos  implements java.io.Serializable {


     private Integer idFavoritos;
     private Anuncio anuncio;
     private Usuario usuario;

    public Favoritos() {
    }

    public Favoritos(Anuncio anuncio, Usuario usuario) {
       this.anuncio = anuncio;
       this.usuario = usuario;
    }
   
    public Integer getIdFavoritos() {
        return this.idFavoritos;
    }
    
    public void setIdFavoritos(Integer idFavoritos) {
        this.idFavoritos = idFavoritos;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


