package hibernateModel;
// Generated 03-abr-2023 13:06:50 by Hibernate Tools 4.3.1


import java.util.Comparator;
import java.util.Date;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer idMensaje;
     private Chat chat;
     private Usuario usuarioByIdRemitente;
     private Usuario usuarioByIdDestinatario;
     private String mensaje;
     private Date fechaHora;

    public Mensaje() {
    }

    public Mensaje(Chat chat, Usuario usuarioByIdRemitente, Usuario usuarioByIdDestinatario, String mensaje, Date fechaHora) {
       this.chat = chat;
       this.usuarioByIdRemitente = usuarioByIdRemitente;
       this.usuarioByIdDestinatario = usuarioByIdDestinatario;
       this.mensaje = mensaje;
       this.fechaHora = fechaHora;
    }
   
    public Integer getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(Integer idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Chat getChat() {
        return this.chat;
    }
    
    public void setChat(Chat chat) {
        this.chat = chat;
    }
    public Usuario getUsuarioByIdRemitente() {
        return this.usuarioByIdRemitente;
    }
    
    public void setUsuarioByIdRemitente(Usuario usuarioByIdRemitente) {
        this.usuarioByIdRemitente = usuarioByIdRemitente;
    }
    public Usuario getUsuarioByIdDestinatario() {
        return this.usuarioByIdDestinatario;
    }
    
    public void setUsuarioByIdDestinatario(Usuario usuarioByIdDestinatario) {
        this.usuarioByIdDestinatario = usuarioByIdDestinatario;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }


public static class MensajeComparator implements Comparator<Mensaje> {
        @Override
        public int compare(Mensaje mensaje1, Mensaje mensaje2) {
            return mensaje1.getFechaHora().compareTo(mensaje2.getFechaHora());
        }
    }

}


