package hibernateModel;
// Generated 03-abr-2023 13:06:50 by Hibernate Tools 4.3.1



/**
 * Notificacion generated by hbm2java
 */
public class Notificacion  implements java.io.Serializable {


     private Integer idNotificacion;
     private Anuncio anuncio;
     private Mensajerestriccion mensajerestriccion;
     private Usuario usuario;
     private boolean revisado;

    public Notificacion() {
    }

    public Notificacion(Anuncio anuncio, Mensajerestriccion mensajeresnotificacion, Usuario usuario, boolean revisado) {
       this.anuncio = anuncio;
       this.mensajerestriccion = mensajeresnotificacion;
       this.usuario = usuario;
       this.revisado=revisado;
    }
   
    public Integer getIdNotificacion() {
        return this.idNotificacion;
    }
    
    public void setIdNotificacion(Integer idNotificacion) {
        this.idNotificacion = idNotificacion;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }

    public Mensajerestriccion getMensajerestriccion() {
        return mensajerestriccion;
    }

    public void setMensajerestriccion(Mensajerestriccion mensajerestriccion) {
        this.mensajerestriccion = mensajerestriccion;
    }
   
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public boolean isRevisado() {
        return revisado;
    }

    public void setRevisado(boolean revisado) {
        this.revisado = revisado;
    }




}


