package hibernateModel;
// Generated 31-may-2023 18:36:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {


     private Integer idOferta;
     private Anuncio anuncio;
     private Usuario usuario;
     private BigDecimal precioOferta;
     private boolean revisado;

    public Oferta() {
    }

    public Oferta(Anuncio anuncio, Usuario usuario, BigDecimal precioOferta, boolean revisado) {
       this.anuncio = anuncio;
       this.usuario = usuario;
       this.precioOferta = precioOferta;
       this.revisado=revisado;
    }
   
    public Integer getIdOferta() {
        return this.idOferta;
    }
    
    public void setIdOferta(Integer idOferta) {
        this.idOferta = idOferta;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public BigDecimal getPrecioOferta() {
        return this.precioOferta;
    }
    
    public void setPrecioOferta(BigDecimal precioOferta) {
        this.precioOferta = precioOferta;
    }

    public boolean isRevisado() {
        return revisado;
    }

    public void setRevisado(boolean revisado) {
        this.revisado = revisado;
    }




}


