package hibernateModel;
// Generated 03-abr-2023 13:06:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String tipoRol;
    

    public Rol() {
    }

	
    public Rol(String tipoRol) {
        this.tipoRol = tipoRol;
    }
    
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getTipoRol() {
        return this.tipoRol;
    }
    
    public void setTipoRol(String tipoRol) {
        this.tipoRol = tipoRol;
    }
   
}


