package hibernateModel;
// Generated 03-abr-2023 13:06:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String contraseña;
     private Date fechaNacimiento;
     private String direccion;
     
     private Set compras = new HashSet(0);
     private Set notificaciones = new HashSet(0);
     private Set ofertas = new HashSet(0);
     private Set favoritos = new HashSet(0);
     private Set valoraciones = new HashSet(0);
     private Set Roles = new HashSet(0);
     private Set anuncios = new HashSet(0);
     
     private Set ChatsMisProductos = new HashSet(0);
     private Set ChatsHaciaAnuncios = new HashSet(0);
     

    public Usuario() {
    }

    
	
    public Usuario(String nombre, String contraseña, Date fechaNacimiento, String direccion) {
        this.nombre = nombre;
        this.contraseña = contraseña;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
    }
    public Usuario(String nombre, String contraseña, Date fechaNacimiento, String direccion, Set compras, Set moderadors, Set notificacions, Set ofertas, Set favoritoses, Set tieneRols, Set anuncios, Set mensajesForIdRemitente, Set chatsForIdUuarioInteresado, Set mensajesForIdDestinatario, Set chatsForIdPropietario, Set valoracions) {
       this.nombre = nombre;
       this.contraseña = contraseña;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.compras = compras;
       this.notificaciones = notificacions;
       this.ofertas = ofertas;
       this.favoritos = favoritoses;
       this.Roles = tieneRols;
       this.anuncios = anuncios;
       this.ChatsMisProductos = chatsForIdUuarioInteresado;
       this.valoraciones = valoracions;
    }

    public Integer getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getContraseña() {
        return contraseña;
    }

    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }

    public Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public Set getCompras() {
        return compras;
    }

    public void setCompras(Set compras) {
        this.compras = compras;
    }

  

    public Set getNotificaciones() {
        return notificaciones;
    }

    public void setNotificaciones(Set notificaciones) {
        this.notificaciones = notificaciones;
    }

    public Set getOfertas() {
        return ofertas;
    }

    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }

    public Set getFavoritos() {
        return favoritos;
    }

    public void setFavoritos(Set favoritos) {
        this.favoritos = favoritos;
    }

    public Set getValoraciones() {
        return valoraciones;
    }

    public void setValoraciones(Set valoraciones) {
        this.valoraciones = valoraciones;
    }

    public Set getRoles() {
        return Roles;
    }

    public void setRoles(Set Roles) {
        this.Roles = Roles;
    }

    public Set getAnuncios() {
        return anuncios;
    }

    public void setAnuncios(Set anuncios) {
        this.anuncios = anuncios;
    }

    public Set getChatsMisProductos() {
        return ChatsMisProductos;
    }

    public void setChatsMisProductos(Set ChatsMisProductos) {
        this.ChatsMisProductos = ChatsMisProductos;
    }

    public Set getChatsHaciaAnuncios() {
        return ChatsHaciaAnuncios;
    }

    public void setChatsHaciaAnuncios(Set ChatsHaciaAnuncios) {
        this.ChatsHaciaAnuncios = ChatsHaciaAnuncios;
    }
}


