package hibernateModel;
// Generated 03-abr-2023 13:06:50 by Hibernate Tools 4.3.1



/**
 * Valoracion generated by hbm2java
 */
public class Valoracion  implements java.io.Serializable {


     private Integer idValoracion;
     private Usuario usuario;
     private int rating;

    public Valoracion() {
    }

    public Valoracion(Usuario usuario,  int rating) {
       this.usuario = usuario;
       this.rating = rating;
    }
   
    public Integer getIdValoracion() {
        return this.idValoracion;
    }
    
    public void setIdValoracion(Integer idValoracion) {
        this.idValoracion = idValoracion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }




}


